name: Testes Automaticos

on: [push]

jobs:
  testar:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Baixar o código
        uses: actions/checkout@v4

      - name: 2. Instalar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 3. Instalar dependências (Jest)
        run: npm install

      - name: 4. Executar bateria de testes
        run: npm test